spring.application.name=client

server.port=8081

#proprietà di  serializzazione (per rendere messaaggio inviabile)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.bootstrap-servers=kafka:9092